# Generated by Django 3.0.5 on 2020-04-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200410_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinternshipprofile',
            name='application_count',
        ),
    ]
